# Generated by Django 2.0.3 on 2018-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.BooleanField(default=True),
        ),
    ]
