# Generated by Django 2.0.3 on 2019-01-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181201_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('items_in_menu', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('items', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='num_toppings',
            field=models.IntegerField(),
        ),
    ]
