# Generated by Django 2.0.3 on 2019-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190117_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='mtype',
            field=models.CharField(default='pasta', max_length=5),
        ),
    ]
