# Generated by Django 2.0.3 on 2019-01-22 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190122_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='id',
        ),
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
